# Generated by Django 5.1.3 on 2024-12-07 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scenario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.scenario'),
            preserve_default=False,
        ),
    ]
