# Generated by Django 5.1.3 on 2024-12-07 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_scenario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.scenario'),
        ),
    ]
