# Generated by Django 5.1.3 on 2024-12-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_scenario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='scenario',
        ),
    ]
