# Generated by Django 5.1.3 on 2024-12-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='beggining_date',
            new_name='beginning_date',
        ),
    ]
