# Generated by Django 5.1.3 on 2024-12-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='beggining_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='end_date',
        ),
    ]
