# Generated by Django 5.1.3 on 2024-12-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_rename_beggining_date_game_beginning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='correct_answer',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
