# Generated by Django 5.1.3 on 2024-12-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_task_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='answer_type',
            field=models.TextField(default='text'),
        ),
        migrations.AlterField(
            model_name='task',
            name='correct_answer',
            field=models.TextField(default=None, null=True),
        ),
    ]
