# Generated by Django 5.1.3 on 2024-12-19 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='correct_answer',
            new_name='correct_text_answer',
        ),
    ]
