# Generated by Django 5.1.3 on 2024-12-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_rename_correct_answer_task_correct_text_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CorrectImages', to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='IncorrectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IncorrectImages', to='tasks.task')),
            ],
        ),
    ]
