# Generated by Django 5.1.3 on 2024-12-27 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_correctimages_incorrectimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incorrectimages',
            name='task',
        ),
        migrations.CreateModel(
            name='AnswerImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IncorrectImages', to='tasks.task')),
            ],
        ),
        migrations.DeleteModel(
            name='CorrectImages',
        ),
        migrations.DeleteModel(
            name='IncorrectImages',
        ),
    ]
