# Generated by Django 5.1.3 on 2025-01-05 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_team_completedtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='team',
        ),
        migrations.AddField(
            model_name='completedtask',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completedTasks', to='tasks.user'),
        ),
    ]
