# Generated by Django 5.1.3 on 2025-01-05 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_completedtask_team_completedtask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completedTasks', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='completedtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completedTasks', to='tasks.user'),
        ),
    ]
