# Generated by Django 5.1.3 on 2025-01-17 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_remove_completedtask_user_completedtask_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='answerimages',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnswerImages', to='tasks.task'),
        ),
    ]
