# Generated by Django 5.1.3 on 2025-01-26 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_team_players_number_alter_answerimages_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='game',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='completedTasks', to='tasks.game'),
            preserve_default=False,
        ),
    ]
