# Generated by Django 5.1.3 on 2025-01-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_completedtask_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='game',
        ),
    ]
